# This flake was initially generated by fh, the CLI for FlakeHub (version 0.1.21)
{
  # A helpful description of your flake
  description = "Add to telegram group scirpt";

  # Flake inputs
  inputs = {
    flake-compat.url = "https://flakehub.com/f/edolstra/flake-compat/*";

    flake-schemas.url = "https://flakehub.com/f/DeterminateSystems/flake-schemas/*";

    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/*";
  };

  # Flake outputs that other flakes can use
  outputs = { self, flake-compat, flake-schemas, nixpkgs }:
    let
      # Helpers for producing system-specific outputs
      supportedSystems = [ "x86_64-linux" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit system; };
      });
    in
    {
      # Schemas tell Nix about the structure of your flake's outputs
      schemas = flake-schemas.schemas;

      # Development environments
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          # Pinned packages available in the environment
          packages = with pkgs; [
            python311
            (with python311Packages; [
              pip
              virtualenv
              pipenv
              curl
              nixpkgs-fmt
            ])
          ];

          # A hook run every time you enter the environment
          shellHook = ''
            	    echo "Setting up Python virtual environment..."
            	    if [ ! -d .venv ]; then
            	    python3 -m venv .venv
            	    echo "Virtual environment created."
            	    fi
            	    source .venv/bin/activate
            	    echo "Installing dependencies from requirements.txt..."
            	    pip install -r requirements.txt
          '';
        };
      });
    };
}
